name: "P6m Release Action"
description: "Tags and commits changes"
author: "Ali Samji <ali@ybor.ai>"

# Define the inputs for this action
inputs:
  tags:
    description: Newline-separated list of tags to create
    required: true
  commit_message:
    description: Commit message for the changes
    required: false
    default: "[skip ci] chore: Release changes."

# Define the runs configuration
runs:
  using: "composite"
  steps:

    - name: Get P6M YBOR Token
      id: p6m-ybor
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        set -euo pipefail
        ACTIONS_TOKEN=$(curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -er '.value')
        RESPONSE=$(curl -X POST \
            -H "x-github-token: $GITHUB_TOKEN" \
            -H "x-actions-token: $ACTIONS_TOKEN" \
            -H "x-installation-id: $PLATFORM_INSTALLATION_ID" \
            $PLATFORM_TOKEN_EXCHANGE_URL)
        ERROR=$(echo "$RESPONSE" | jq -r '.error')
        if [ "$ERROR" -ne 'null' ]; then
          echo "Error: $ERROR"
          exit 1
        fi
        echo token=$(echo "$RESPONSE" | jq -er '.token') >> $GITHUB_OUTPUT
        STATUS=$(echo "$RESPONSE" | jq -er '.status')
        echo status=$STATUS >> $GITHUB_OUTPUT
        echo "Status: $STATUS"

    - name: Release Version
      shell: bash
      env:
        GH_TOKEN: ${{ steps.p6m-ybor.outputs.token }}
      run: |
        ${{ github.action_path }}/commit_and_tag.sh ${{ inputs.tags }} '${{ inputs.commit_message }}'

# Define the branding for the action in the GitHub Marketplace
branding:
  icon: "award"
  color: "blue"
